### ISSUE TITLE
 compile libevent-srcs failed 

### ISSUE THREAD

**Issue by JamesWuChina** [google/ecclesia-machine-management#144]
Hi,guys.
   when I compile the code by:bazelisk build //ecclesia/... have some error below.how can i fix that.thanks.
ERROR: /root/.cache/bazel/_bazel_root/a967d5377f9712632b65ecbee322374a/external/com_github_libevent_libevent/BUILD.bazel:49:8: Executing genrule @com_github_libevent_libevent//:libevent-srcs failed: (Exit 127): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
./autogen.sh: 18: ./autogen.sh: aclocal: not found
ERROR: /root/.cache/bazel/_bazel_root/a967d5377f9712632b65ecbee322374a/external/com_github_libevent_libevent/BUILD.bazel:66:11 Middleman _middlemen/@com_Ugithub_Ulibevent_Ulibevent_S_S_Clibevent-BazelCppSemantics_build_arch_k8-fastbuild failed: (Exit 127): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 1.404s, Critical Path: 1.01s
INFO: 10 processes: 5 internal, 5 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by dchanman** [comment]
Hi James, are you still seeing this issue?

You need to make sure your own machine meets some minimum requirements. This seems like autotools-dev is a requirement to libevent and you'll have to apt-get install it.

**Comment by dchanman** [comment]
Apologies for the slow response. Hopefully our WORKSPACE has been updated to the point where your system will be able to build this project. Let us know if the issue persists.
